[rocks]

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[plugins]
"rocks.nvim" = "2.46.1"
"rocks-git.nvim" = "2.5.6"
"rocks-config.nvim" = "3.1.2"
"rocks-lazy.nvim" = "1.2.2"
"rocks-dev.nvim" = "1.8.1"

# +----------------------------------------------------------+
# | Colorschemes                                             |
# +----------------------------------------------------------+
"nvim-web-devicons" = { git = "nvim-tree/nvim-web-devicons", rev = "8dcb311b0c92d460fac00eac706abd43d94d68af" }
"nvim" = { git = "catppuccin/nvim", rev = "v1.11.0" }
"tiny-devicons-auto-colors.nvim" = { git = "rachartier/tiny-devicons-auto-colors.nvim", rev = "51f548421f8a74680eff27d283c9d5ea6e8d0074" }
"mini.icons" = "0.16.0"
"mini.hipatterns" = "0.16.0"

# +----------------------------------------------------------+
# | Editor                                                   |
# +----------------------------------------------------------+

# +- Vim Built-in Enhancements ------------------------------+
"highlight-undo.nvim" = { git = "tzachar/highlight-undo.nvim", rev = "ee32e12693d70e66f954d09a504a7371d110fc27" }
"mini.misc" = "0.16.0"
"nvim-origami" = { git = "chrisgrieser/nvim-origami", rev = "d5e8429e588deabe9b32a7d80be3292e89833100" }
"vim-matchup" = { git = "andymass/vim-matchup", rev = "1c276e12b49a83c1bdca74351187b8adea5da4b9" }
"yanky.nvim" = { git = "gbprod/yanky.nvim", rev = "04775cc6e10ef038c397c407bc17f00a2f52b378" }
"jumppack.nvim" = { git = "suliatis/jumppack.nvim", rev = "c1bc410ef011afbd405e945a08ce200d59a0e537" }

# +- Visual Enhancements ------------------------------------+
"indent-blankline.nvim" = "3.9.0"
"vim-illuminate" = { git = "rrethy/vim-illuminate", rev = "0d1e93684da00ab7c057410fecfc24f434698898" }

# +- Vim Motions --------------------------------------------+
"flash.nvim" = "2.1.0"
"mini.align" = "0.16.0"
"mini.ai" = "0.16.0"
"mini.extra" = "0.16.0"  # only used for mini.ai text object
"mini.splitjoin" = "0.16.0"
"nvim-spider" = { git = "chrisgrieser/nvim-spider", rev = "5565cc9ee3a7da9d0ba7504380bd2b0cb43cbbc0" }
"nvim-surround" = { version = "3.1.7" }
"treewalker.nvim" = { git = "aaronik/treewalker.nvim", rev = "fb93a6cd02a0445da7976ef5646b7fbd3c2d7ee3" }
"vim-repeat" = { git = "tpope/vim-repeat", rev = "v1.2" }

# +- Miscellenous -------------------------------------------+
"guess-indent.nvim" = { git = "NMAC427/guess-indent.nvim", rev = "84a4987ff36798c2fc1169cbaff67960aed9776f", config = true }

# +----------------------------------------------------------+
# | Integrated Development Environment                       |
# +----------------------------------------------------------+

# +- Comments / Documentation -------------------------------+
"debugprint.nvim" = { git = "andrewferrier/debugprint.nvim", rev = "v6.3.0" }

# +- Completion ---------------------------------------------+
"blink.cmp" = { git = "saghen/blink.cmp", rev = "v1.8.0" }
# +- Completion: Sources ------------------------------------+
"blink.compat" = { git = "saghen/blink.compat", rev = "v2.5.0" }
"blink-ripgrep.nvim" = { git = "mikavilpas/blink-ripgrep.nvim", rev = "v2.2.0" }
"blink-cmp-conventional-commits" = { git = "disrupted/blink-cmp-conventional-commits", rev = "59d7e5fe69c7953fd9568773d70006f5b48bbf3b" }
"blink-cmp-env" = { git = "bydlw98/blink-cmp-env", rev = "99af62c1f9aa46005e8f50ad4ccee581946546ca" }
"blink-cmp-git" = { git = "kaiser-yang/blink-cmp-git", rev = "v3.0.0" }
"cmp-bufname" = { git = "rasulomaroff/cmp-bufname", rev = "e6ea451b13ff0942232bad19ea6f2bd8929aa86c" }
"cmp-dap" = { git = "rcarriga/cmp-dap", rev = "ea92773e84c0ad3288c3bc5e452ac91559669087" }
"cmp-vimtex" = { git = "micangl/cmp-vimtex", rev = "5283bf9108ef33d41e704027b9ef22437ce7a15b" }
"nvim-html-css" = { git = "jezda1337/nvim-html-css", rev = "9d5fe0b9a4180b960ef92a2cfe8534f3e2c4f957" }
# +- Completion: Copilot-------------------------------------+
"copilot.vim" = { git = "github/copilot.vim", rev = "v1.57.0" }
"sidekick.nvim" = { git = "folke/sidekick.nvim", rev = "v2.1.0" }
# +- Completion: Extras -------------------------------------+
"colorful-menu.nvim" = { git = "xzbdmw/colorful-menu.nvim", rev = "b51a659459df8d078201aefc995db8175ed55e84" }
"luasnip" = { git = "l3mon4d3/luasnip", rev = "v2.4.1" }
"nvim-scissors" = { git = "chrisgrieser/nvim-scissors", rev = "8846bae15295fa5843b0c79cd6b8dd07a941c85d" }

# +- Debugging ----------------------------------------------+
"nvim-dap" = { git = "mfussenegger/nvim-dap", rev = "5860c7c501eb428d3137ee22c522828d20cca0b3" }
"nvim-dap-ui" = { git = "rcarriga/nvim-dap-ui", rev = "cf91d5e2d07c72903d052f5207511bf7ecdb7122" }
"debugmaster.nvim" = { git = "miroshqa/debugmaster.nvim", rev = "3d144b98c2c23f39123fbf5f10fdff7d6480a0e6" }
"nvim-dap-virtual-text" = { git = "theHamsta/nvim-dap-virtual-text", rev = "fbdb48c2ed45f4a8293d0d483f7730d24467ccb6" }
"nvim-dap-repl-highlights" = { git = "liadoz/nvim-dap-repl-highlights", rev = "f31deba47fe3ee6ff8d2f13d9dbd06b2d1ae06b5" }
"goto-breakpoints.nvim" = { git = "ofirgall/goto-breakpoints.nvim", rev = "d14776899eda4023667b246e5c53c14a7c41f88e" }
# FIXME: remove after https://github.com/mfussenegger/nvim-dap/issues/1388

# +- Git ----------------------------------------------------+
"neogit" = { git = "NeogitOrg/neogit", rev = "451e57fa3633c935c4c32c669ad5aa447d3db257" }
"git-conflict.nvim" = { git = "akinsho/git-conflict.nvim", rev = "v2.1.0" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim", rev = "v1.0.2" }
"diffview.nvim" = { git = "sindrets/diffview.nvim", rev = "4516612fe98ff56ae0415a259ff6361a89419b0a" }

# +- Language Server Protocol -------------------------------+
"fastaction.nvim" = { git = "chaitanyabsprip/fastaction.nvim", rev = "v2.0.1" }
"lensline.nvim" = { git = "oribarilan/lensline.nvim", rev = "ee938078aeee9751aafc20b055fcbb8aa579bb76" }
"lsplinks.nvim" = { git = "icholy/lsplinks.nvim", rev = "v1.0.0" }
"glance.nvim" = { git = "DNLHC/glance.nvim", rev = "bf86d8b79dce808e65fdb6e9269d0b4ed6d2eefc" }
"hover.nvim" = { git = "lewis6991/hover.nvim", rev = "3b49066e09e03e63be6d6f43ae2b8bcd58301f63" }
"workspace-diagnostics.nvim" = { git = "artemave/workspace-diagnostics.nvim", rev = "60f9175b2501ae3f8b1aba9719c0df8827610c8e" }
"output-panel.nvim" = { git = "mhanberg/output-panel.nvim", rev = "a60079820cd80484925e8130b7b52052b08eb153", config = true }
"overlook.nvim" = { git = "williamhsieh/overlook.nvim", rev = "6f74f20a61204275989050a2c1221bdc53b534c4" }
"garbage-day.nvim" = { git = "zeioth/garbage-day.nvim", rev = "v1.3.1" }

# +- Search -------------------------------------------------+
"grug-far.nvim" = { git = "magicduck/grug-far.nvim", rev = "1.6.53" }

# +- Session and Project Management -------------------------+
"resession.nvim" = { git = "stevearc/resession.nvim", rev = "v1.2.1" }

# +- Test ---------------------------------------------------+
"neotest" = "5.13.4"

# +- Tooling ------------------------------------------------+
"conform.nvim" = "9.1.0"
"nvim-lint" = { git = "mfussenegger/nvim-lint", rev = "d1118791070d090777398792a73032a0ca5c79ff" }
"nvim-rulebook" = { git = "chrisgrieser/nvim-rulebook", rev = "8f35bf80608a9768bd36c14a91879d778206eef3" }

# +- Treesitter ---------------------------------------------+
"rocks-treesitter.nvim" = "1.3.1"
"nvim-treesitter-legacy-api" = { git = "nvim-treesitter/nvim-treesitter", rev = "v0.10.0" }
# +- Treesitter: Pairs --------------------------------------+
"nvim-autopairs" = { git = "windwp/nvim-autopairs", rev = "7a2c97cccd60abc559344042fefb1d5a85b3e33b" }
"clasp.nvim" = { git = "xzbdmw/clasp.nvim", rev = "25442429aae1b1de0627f358740613f77ec57410" }
"tabout.nvim" = { git = "abecodes/tabout.nvim", rev = "9a3499480a8e53dcaa665e2836f287e3b7764009" }
# +- Treesitter: Modules ------------------------------------+
"rainbow-delimiters.nvim" = "0.10.0"
"nvim-ts-autotag" = "scm"
"nvim-ts-context-commentstring" = "scm"
"nvim-treesitter-endwise" = { git = "RRethy/nvim-treesitter-endwise", rev = "a61a9de7965324d4019fb1637b66bfacdcb01f51" }
"nvim-treesitter-textsubjects" = { git = "RRethy/nvim-treesitter-textsubjects", rev = "9e3edd38e44c8f3af5634c5e30a33ebd79227f11" }
"nvim-treesitter-textobjects" = { git = "nvim-treesitter/nvim-treesitter-textobjects", rev = "5ca4aaa6efdcc59be46b95a3e876300cfead05ef" }

# +----------------------------------------------------------+
# | Language Support                                         |
# +----------------------------------------------------------+

# +- LSP ----------------------------------------------------+
"nvim-lspconfig" = "2.5.0"
"mason.nvim" = { git = "mason-org/mason.nvim", rev = "v2.1.0" }
"neoconf.nvim" = { git = "folke/neoconf.nvim", rev = "8afa42277fa944f60071241b37e922b6f2d9a9f8" }
"otter.nvim" = "2.13.2"

# +- Config -------------------------------------------------+
"schemastore.nvim" = { git = "b0o/SchemaStore.nvim", rev = "aa25399c48236b77af71d4b64cdf157d2ba4e990" }
# +- HTTP ---------------------------------------------------+
"kulala.nvim" = { git = "mistweaverco/kulala.nvim", rev = "v5.3.3", ft = "http" }
# +- LaTeX --------------------------------------------------+
"vimtex" = { git = "lervag/vimtex", rev = "v2.17" }
# +- Lua ----------------------------------------------------+
"lazydev.nvim" = { git = "folke/lazydev.nvim", rev = "v1.10.0" }
"luvit-meta" = { git = "Bilal2453/luvit-meta", rev = "0ea4ff636c5bb559ffa78108561d0976f4de9682" }
# +- Markdown -----------------------------------------------+
# "render-markdown.nvim" = { git = "MeanderingProgrammer/render-markdown.nvim", rev = "v8.4.0" }
"markview.nvim" = "27.0.0"
"obsidian.nvim" = "3.14.6"
"vivify.vim" = { git = "jannis-baum/vivify.vim", rev = "99a1539a440633ee7a164e094a736c04acc2335d" }
"table-nvim" = { git = "scjangra/table-nvim", rev = "287056dab467bce5c34d288c47467856db4f7457" }
# +- Python -------------------------------------------------+
"python.nvim" = { git = "joshzcold/python.nvim", rev = "197a15b3e91ccd5ab550e15d45eb1b18445ed10a" }
"neotest-python" = { git = "nvim-neotest/neotest-python", rev = "b0d3a861bd85689d8ed73f0590c47963a7eb1bf9" }
"nvim-dap-python" = "scm"
# +- Rust ---------------------------------------------------+
"rustaceanvim" = "6.9.7"
# +- Vim ----------------------------------------------------+
"one-small-step-for-vimkind" = { git = "jbyuki/one-small-step-for-vimkind", rev = "87eeca2bd4d90a94eed1ef0dbc66885117e7bacb" }
# +- Web ----------------------------------------------------+
"typescript-tools.nvim" = { git = "pmizio/typescript-tools.nvim", rev = "c2f5910074103705661e9651aa841e0d7eea9932" }
"tailwind-tools.nvim" = { git = "luckasRanarison/tailwind-tools.nvim", rev = "v0.3.2" }
# +- Minor Languages ----------------------------------------+
"chezmoi.vim" = { git = "alker0/chezmoi.vim", rev = "73b30df35c6b645ebd2e6a440eea8463ef3c3f47" }
"csvview.nvim" = { git = "hat0uma/csvview.nvim", rev = "v1.3.0" }
"nvim-ansible" = { git = "mfussenegger/nvim-ansible", rev = "bba61168b7aef735e7f950fdfece5ef6c388eacf" }
"nvim-parinfer" = "1.2.0"
"vim-sage" = { git = "petRUShka/vim-sage", rev = "4b036eead948e3ae1d414efdeefe11f7543fc366" }
"yuck.vim" = { git = "elkowar/yuck.vim", rev = "9b5e0370f70cc30383e1dabd6c215475915fe5c3" }

# +----------------------------------------------------------+
# | User Interface                                           |
# +----------------------------------------------------------+

"edgy.nvim" = "1.10.2"
"no-neck-pain.nvim" = "2.5.2"

# +- Buffer Switcher ----------------------------------------+
"dart.nvim" = { git = "iofq/dart.nvim", rev = "8822aabbfef95eda2b22a8f7ee08912c762ef941" }

# +- LLM ----------------------------------------------------+
"gp.nvim" = { git = "robitx/gp.nvim", rev = "v3.9.0" }
"codecompanion.nvim" = { git = "olimorris/codecompanion.nvim", rev = "v17.33.0" }
"codecompanion-history.nvim" = { git = "ravitemer/codecompanion-history.nvim", rev = "eb99d256352144cf3b6a1c45608ec25544a0813d" }
"codecompanion-spinner.nvim" = { git = "franco-ruggeri/codecompanion-spinner.nvim", rev = "v0.2.3" }
"vectorcode" = { git = "davidyz/vectorcode", rev = "0.7.19" }
"mcphub.nvim" = { git = "ravitemer/mcphub.nvim", rev = "v6.2.0" }

# +- File Explorer ------------------------------------------+
"neo-tree.nvim" = "3.38.0"
"nvim-window-picker" = { git = "s1n7ax/nvim-window-picker", rev = "v2.4.0" }
"oil.nvim" = "2.15.0"

# +- Notifications ------------------------------------------+
"fidget.nvim" = "1.6.0"

# +- Outline ------------------------------------------------+
"aerial.nvim" = "2.6.1"
"namu.nvim" = { git = "bassamsdata/namu.nvim", rev = "51d2c1de7dcdab8c0b712cd9463e392039efa5e2" }

# +- Runner (Overseer) --------------------------------------+
"overseer.nvim" = { git = "stevearc/overseer.nvim", rev = "v1.6.0" }

# +- Statusline ---------------------------------------------+
"lualine.nvim" = "scm"
"lualine-pretty-path" = { git = "bwpge/lualine-pretty-path", rev = "852cb06f3562bced4776a924e56a9e44d0ce634f" }
# -- Breadcrumbs
"nvim-navic" = { git = "SmiteshP/nvim-navic", rev = "7d914a39a1ef8f4e22c2c4381abeef7c556f5a13" }
# -- Context
"nvim-treesitter-context" = { git = "nvim-treesitter/nvim-treesitter-context", rev = "660861b1849256398f70450afdf93908d28dc945" }

# +- Quickfix -----------------------------------------------+
"trouble.nvim" = "3.7.1"

# +- Miscelleneous ------------------------------------------+
"icon-picker.nvim" = "scm"
"todo-comments.nvim" = "1.5.0"
"which-key.nvim" = "3.17.0"

# +----------------------------------------------------------+
# | Miscelleneous                                            |
# +----------------------------------------------------------+

"gitignore.nvim" = { git = "wintermute-cell/gitignore.nvim", rev = "0344f643768c4d64af4add8c1bdddf6f7d4c9010" }
"snacks.nvim" = { git = "folke/snacks.nvim", rev = "v2.30.0", opt = true }
"codesnap.nvim" = { git = "mistricky/codesnap.nvim", rev = "v1.6.3" }

# +----------------------------------------------------------+
# | Dependencies                                             |
# +----------------------------------------------------------+
"nvim-nio" = "1.10.1"  # pytest
"plenary.nvim" = { git = "nvim-lua/plenary.nvim", rev = "b9fd5226c2f76c951fc8ed5923d85e4de065e509" }  # codecompanion, typescript-tools.nvim, dart.nvim
"jsregexp" = "0.1.0"  # luasnip

# +----------------------------------------------------------+
# | Parsers                                                  |
# +----------------------------------------------------------+
tree-sitter-asm = "0.0.33"
tree-sitter-bash = "0.0.46"
tree-sitter-bibtex = "0.0.32"
tree-sitter-cpp = "0.0.49"
tree-sitter-css = "0.0.39"
tree-sitter-csv = "0.0.30"
tree-sitter-diff = "0.0.33"
tree-sitter-dockerfile = "0.0.30"
tree-sitter-ecma = "0.0.33"
tree-sitter-editorconfig = "0.0.60"
tree-sitter-gitcommit = "0.0.34"
tree-sitter-gitignore = "0.0.29"
tree-sitter-git_config = "0.0.31"
tree-sitter-git_rebase = "0.0.29"
tree-sitter-go = "0.0.43"
tree-sitter-html = "0.0.40"
tree-sitter-htmldjango = "0.0.30"
tree-sitter-html_tags = "0.0.29"
tree-sitter-http = "0.0.37"
tree-sitter-hyprlang = "0.0.40"
tree-sitter-ini = "0.0.34"
tree-sitter-javascript = "0.0.41"
tree-sitter-jinja = "0.0.10"
tree-sitter-jsx = "0.0.30"
tree-sitter-jq = "0.0.30"
tree-sitter-kitty = { git = "oxy2dev/tree-sitter-kitty", rev = "v0.0.1" }
# tree-sitter-latex = "scm"
tree-sitter-lua = "0.0.36"
tree-sitter-luadoc = "0.0.30"
tree-sitter-markdown = "0.0.45"
tree-sitter-markdown_inline = "0.0.43"
tree-sitter-pem = "0.0.32"
tree-sitter-perl = "0.0.47"
tree-sitter-php = "0.0.50"
tree-sitter-pug = "0.0.30"
tree-sitter-python = { git = "tree-sitter/tree-sitter-python", rev = "26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64" }
tree-sitter-query = "0.0.45"
tree-sitter-requirements = "0.0.31"
tree-sitter-rst = "0.0.33"
tree-sitter-rust = "0.0.55"
tree-sitter-ssh_config = "0.0.34"
tree-sitter-svelte = "0.0.33"
tree-sitter-tsx = "0.0.37"
tree-sitter-toml = "0.0.31"
tree-sitter-typescript = "0.0.38"
tree-sitter-xml = "0.0.42"
tree-sitter-vim = "0.0.37"
tree-sitter-vimdoc = "0.0.36"
tree-sitter-vue = "0.0.33"
tree-sitter-yaml = "0.0.37"
tree-sitter-yuck = "0.0.29"
tree-sitter-nix = "0.0.66"

# +----------------------------------------------------------+
# | Config                                                   |
# +----------------------------------------------------------+

[config]
plugins_dir = "_plugins/"
auto_setup = false

[dev]
path = "/home/quitlox/Workspace/neovim-plugins"

# +----------------------------------------------------------+
# | Graveyard                                                |
# +----------------------------------------------------------+
# "marks.nvim" = { git = "chentoast/marks.nvim" }
# "dial.nvim" = "0.4.0"

# "nvim-hlslens" = { git = "kevinhwang91/nvim-hlslens", rev = "0bd7ddb0aecf095055e9cb6eef0c25c70fb69cfc", pin = true } # pinned because of outdated release
#     hlslens causes commandline completion to dissapear: https://github.com/kevinhwang91/nvim-hlslens/issues/75

# +- Go -----------------------------------------------------+
# "go.nvim" = { version = "0.10.0", ft = ["go", "gomod"] }
# "guihua.lua" = { git = "ray-x/guihua.lua", rev = "d783191eaa75215beae0c80319fcce5e6b3beeda" } # NOTE: Overwrites fzy which may cause issues (str(fixed for now, but still)), maybe switch to use gopher instead if I ever need it
